Add benchmarks workflow
nuxeo/nuxeo-bench-site pull request #13
Opened 2023-11-24 05:32 UTC by sushildeep

https://jira.nuxeo.com/browse/DEVOPS-183

2023-11-24 05:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-bench-site?pullRequest=13) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-bench-site?pullRequest=13) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-bench-site?pullRequest=13) it.</sub>

2023-11-28 18:42 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      uses: actions/checkout@v2
I guess this can be bumped

2023-11-28 18:42 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      run: /tmp/hugo -t hyde
You might want to take alook at https://github.com/marketplace/actions/hugo-site that builds the site without installation requirements.

2023-11-28 18:42 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      run: ssh root@www "service nginx reload"
This step will require a deplo key and apporpriate server configuration.

2023-11-30 12:16 UTC, alxgomz requested changes

2023-11-30 12:16 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      - main
there is no such branch

2023-11-30 12:16 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      run: ssh root@www "service nginx reload"
let's make sure we fix this before merging

2023-11-30 12:16 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      run: /tmp/hugo -t hyde
don't like it?

2023-11-30 12:39 UTC, alxgomz requested changes

2023-11-30 12:39 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      uses: chabad360/hugo-actions@master
please set`hugoVersion` & `args` params to match what was present before.

2023-11-30 12:39 UTC, alxgomz commented
I'm worried that this is deploying in prod without any prior test.
Were there any test worklow in the previous pipeline?

2023-11-30 12:40 UTC, alxgomz commented
⬆️ @troger ?

2023-11-30 12:52 UTC, sushildeep commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      uses: chabad360/hugo-actions@master
sure

2023-12-01 15:05 UTC, alxgomz requested changes

2023-12-01 15:05 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      uses: chabad360/hugo-actions@master
I forgot to mention it but do not use `master` as a ref. here you can use `v2` which is the latest. That will prevent you from being hit by non-backward compatible changes that may be introduced in master

2023-12-01 15:05 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +        args: hugo -t hyde
you just need the arguments, not the full command. Check the action. doc: https://github.com/chabad360/hugo-actions#-inputs

2023-12-07 08:44 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +      uses: chabad360/hugo-actions@master
as mentionned by @gionn during the daily yesterday we should use SHA hashes and not tags or branch names anymore.

2023-12-07 09:46 UTC, alxgomz requested changes
I have confirmed with @ataillefer that there is no pre-prod server for benchmarks.

2023-12-07 09:46 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +          rsync -Waxv --delete ${{ github.workspace }}/public/ root@www:/var/www/nuxeo.com/benchmarks
I checked on the target server and the files and the directory which holds them belong to `jenkins` (uid 1001).
That means there is no need to rsync as `root`.
Please make sure files are copied with the right ownerships and we do not connect as root.

e.g. using `-a` can be a problem as rsync tends to map users. I think we should really login as jenkins user and avoid `-a` (I see no good reason to use `-W` either) so the outcome is more deterministic

2023-12-07 09:46 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +          rsync -Waxv --delete ${{ github.workspace }}/public/ root@www:/var/www/nuxeo.com/benchmarks
Also avoid using `www` as it relies either on ssh_confg or dns configuration that may not be present.

2023-12-07 09:46 UTC, alxgomz commented on .github/workflows/deploy-nuxeo.com-benchmarks.yml
> +        run: ssh root@www "service nginx reload"
After checking the content of the existing site, we're simply copying static file. We're not modifying any config oand the site do not embed any either.
We should not need to restart the service at all.

2023-12-15 11:03 UTC, alxgomz approved these changes

2023-12-19 10:53 UTC, merged